services:
  basione-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: basione-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env